/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(print_stream.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(814eb3c7574b8f90e8a52136171854fc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora_sdr/print_stream.h>
// pydoc.h is automatically generated in the build directory
#include <print_stream_pydoc.h>

void bind_print_stream(py::module& m)
{

    using print_stream    = gr::lora_sdr::print_stream;


    py::class_<print_stream, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<print_stream>>(m, "print_stream", D(print_stream))

        .def(py::init(&print_stream::make),
           D(print_stream,make)
        )
        



        ;




}








